
language: python
python:
- "3.7-dev"
install:
- make deps
before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d ${HOME}/bin/chromedriver
- export CHROME_BIN=${HOME}/bin/chromedriver

script:
- make test
